### ISSUE TITLE
Issue loading data from Kia Soul 2020

### ISSUE THREAD

**Issue by sindrej** [gruijter/com.gruijter.hyundai_kia#1]
**2021-02-19 22:10:21 [err] [uvo] [0] doPoll failed Cannot read property 'batSoc' of undefined** 
2021-02-19 22:05:17 [log] [uvo] [0] Start polling car SK3 EV 19 @ 5 minute interval 
2021-02-19 22:05:17 [err] [uvo] [0] TypeError: Cannot read property 'batSoc' of undefined at UvoDevice.handleInfo (/drivers/generic_device.js:509:46) at UvoDevice.doPoll (/drivers/generic_device.js:398:9) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async UvoDevice.runQueue (/drivers/generic_device.js:225:5) 
2021-02-19 22:05:17 [log] [uvo] [0] {"value":23492.3,"unit":1} 
2021-02-19 22:05:17 [log] [uvo] [0] {"latitude":61.310092,"longitude":7.221961,"altitude":0,"speed":{"value":0,"unit":0},"heading":0} 
2021-02-19 22:05:17 [log] [uvo] [0] {"airCtrlOn":false,"engine":false,"doorLock":false,"doorOpen":{"frontLeft":0,"frontRight":0,"backLeft":0,"backRight":0},"trunkOpen":false,"airTemp":{"value":"00H","unit":0,"hvacTempType":1},"defrost":false,"acc":false,"evStatus":{"batteryCharge":false,"batteryStatus":88,"batteryPlugin":0,"remainTime2":{"etc1":{"value":78,"unit":1},"etc2":{"value":0,"unit":1},"etc3":{"value":0,"unit":1},"atc":{"value":0,"unit":1}},"drvDistance":[{"rangeByFuel":{"evModeRange":{"value":306,"unit":1},"totalAvailableRange":{"value":306,"unit":1}},"type":2}],"reservChargeInfos":{"reservChargeInfo":{"reservChargeInfoDetail":{"reservInfo":{"day":[9],"time":{"time":"0600","timeSection":0}},"reservChargeSet":false,"reservFatcSet":{"defrost":false,"airTemp":{"value":"00H","unit":0,"hvacTempType":3},"airCtrl":0,"heating1":0}}},"offpeakPowerInfo":{"offPeakPowerTime1":{"starttime":{"time":"1200","timeSection":0},"endtime":{"time":"1200","timeSection":0}},"offPeakPowerFlag":2},"reserveChargeInfo2":{"reservChargeInfoDetail":{"reservInfo":{"day":[9],"time":{"time":"1900","timeSection":1}},"reservChargeSet":false,"reservFatcSet":{"defrost":false,"airTemp":{"value":"00H","unit":0,"hvacTempType":3},"airCtrl":0,"heating1":0}}},"reservFlag":0,"ect":{"start":{"day":9,"time":{"time":"1963","timeSection":1}},"end":{"day":9,"time":{"time":"1963","timeSection":1}}},"targetSOClist":[{"targetSOClevel":100,"dte":{"rangeByFuel":{"evModeRange":{"value":351,"unit":1},"totalAvailableRange":{"value":351,"unit":1}},"type":2},"plugType":0},{"targetSOClevel":80,"dte":{"rangeByFuel":{"evModeRange":{"value":274,"unit":1},"totalAvailableRange":{"value":274,"unit":1}},"type":2},"plugType":1}]}},"ign3":true,"hoodOpen":false,"transCond":true,"steerWheelHeat":0,"sideBackWindowHeat":0,"tirePressureLamp":{"tirePressureLampAll":0,"tirePressureLampFL":0,"tirePressureLampFR":0,"tirePressureLampRL":0,"tirePressureLampRR":0},"time":"20210219230515"} 
2021-02-19 22:05:02 [log] [uvo] [0] Status refresh from car 
2021-02-19 22:04:59 [log] [uvo] [0] Start polling server SK3 EV 19 @ 10 minute interval 
2021-02-19 22:04:59 [log] [uvo] [0] registering listeners 
2021-02-19 22:04:59 [log] [uvo] [0] Google Directions enabled: false 
2021-02-19 22:04:59 [log] [uvo] [0] ABRP enabled: false 
2021-02-19 22:04:59 [log] [uvo] [0] {"nickname":"SK3 EV 19","name":"SK3 EV 19","regDate":"2020-05-13 16:07:49.351","brandIndicator":"H","id":"6b31f1cf-76e8-47c5-85d6-1fb9249334a3","vin":"KNAJ3811FL7000262","generation":"2020"} 
2021-02-19 22:04:55 [log] [uvo] [0] Car added as device: SK3 EV 19 
2021-02-19 22:04:53 [log] [uvo] listing of devices started 
2021-02-19 22:04:53 [log] [uvo] CREDENTIALS OK! 
2021-02-19 22:04:46 [log] [uvo] validating credentials 
2021-02-19 22:03:55 [log] [uvo] Pairing of new car started 
2021-02-19 07:18:09 [log] [uvo] onDriverInit 
2021-02-19 07:18:09 [log] [bluelink] onDriverInit 
2021-02-19 07:17:58 [log] [carApp] Hyundai and Kia app is running... 
2021-02-19 07:17:58 [log] [Homey] capturing stderr 
2021-02-19 07:17:58 [log] [Homey] capturing stdout

**Comment by gruijter** [comment]
Thx 4 reporting. Is this the first time you are using the app, or did you use it before without problem?

**Comment by gruijter** [comment]
![Screenshot_20210220-085701_UVO.jpg](https://user-images.githubusercontent.com/19174120/108588474-b0c64700-7359-11eb-89b2-52cdcd499edf.jpg)

In your UVO app, do you see the battery state at the bottom?

**Comment by gruijter** [comment]
I created a new version that should not crash when the car is not reporting the 12v battery state (because that is what your car is not doing)

Can you please install this version and let me know if that fixes the crash?

https://homey.app/a/com.gruijter.hyundai_kia/test/

**Comment by sindrej** [comment]
I do not have the 12V battery status in the app.

Tested the experimental version and now I'm seeing the following error:

2021-02-20 10:02:07 [log] [uvo] [0] Error: invalid_type at Remote Process measure_battery.12V undefined 
2021-02-20 10:02:07 [log] [uvo] [0] Start polling car SK3 EV 19 @ 5 minute interval 
...

**Comment by gruijter** [comment]
ok, thx. will have to fix that error too then.

**Comment by sindrej** [comment]
Well everything seems to be working even with that error. All data is showing and I can control the car - great job 👍

**Comment by gruijter** [comment]
New version 2.0.2 can be installed using the same link as above. This should get rid of the error. Can you please check? Yhx!

**Comment by gruijter** [comment]
Does 2.0.3 work without the invalid_type error? If so I can push it to stable in the app store.

**Comment by sindrej** [comment]
No errors this time 👍 Great work

**Comment by gruijter** [comment]
Super. Thx for reporting and testing :)
